{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-stream-table.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-stream-table.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "spark-stream-table.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "spark-stream-table.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}

