apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-stream-table.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-stream-table.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "spark-stream-table.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    name: spark-ui
    protocol: TCP

